apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kafka-issuer
spec:
  # Используем самоподписанный сертификат для тестового окружения
  # В продакшене здесь должен быть настоящий CA (например, ACME)
  selfSigned: {}

---
# Для production варианта, можно использовать настоящий CA
# Например, Let's Encrypt через ACME:
#
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: kafka-issuer-prod
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: your-email@example.com
#     privateKeySecretRef:
#       name: letsencrypt-account-key
#     solvers:
#     - http01:
#         ingress:
#           class: nginx 