apiVersion: v1
kind: Secret
metadata:
  name: kafka-ssl-certs
  namespace: spark
  labels:
    app: kafka-spark-integration
    component: ssl-certs
type: Opaque
data:
  # Здесь должны быть base64-закодированные содержимые файлов
  # Пример: cat keystore.jks | base64 > keystore.b64
  keystore.jks: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR3akNDQXFxZ0F3SUJBZ0lVTVd0UTNNWDlNSjNSWlhJNU12Y0JaaFNJWS9rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNVbFV4RWpBUUJnTlZCQWdUQ1VWdFpXeHBibWR5WVdReEVEQU9CZ05WQkFjVApCMDFsYzJOdmR6RXpNREVHQTFVRUNoTXFTVzUwWlhKdVlXd2dSMnJ3bjRlbklFbHVkR1ZuY21GMGFXOXVJRUZrCmJXbHVhWE4wY21GMGFXOXVNUk13RVFZRFZRUURFZ3BRY205a2RXTjBhVzl1TUI0WERUSXpNRFV3T0RFd01UQXcKTUZvWERUTXdNRFV3TmpFd01UQXdNRm93Y3pFTE1Ba0dBMVVFQmhNQ1VsVXhFakFRQmdOVkJBZ1RDVVZvWldScwphVzVuY21Ga01SQXdEZ1lEVlFRSEV3ZE5aWE5qYjNjeE16QXhCZ05WQkFvVEtrXXWJTYHRQkQZWJua2c9PQo=
  truststore.jks: SW5OaEZVdlpZUFVwRnU2M0hWVlZoOGkvCnVCQUpId2NzaFdkRFUzSUZqZWZpZHFFVlVVQ2NlWUhMNjJBd0I4SDFRYS9mdUxDTE4wYUdNNXQrTGh5ZnQ0WTUKOGJZc3QrOXhOSFdycXNjbmdqVXNnZm1qSWJBQmJyTGREWlRUTmJhTWZtL2Y0OXRmUjY3T3ZVVnE2dnlsbC9IMwpnVmNEN2p4aG9zcCt1dkJYcThuZ0JaZUdEV3RQL295MDl5cERSR0RQbGNQL2lhejdYNzlZY3daU2RnTzE5ak9RCk5mbExWOFdCcnUwRIFQZE1QNmxSeGdHSC9TTzJEV3pFRVNpZHRRaWRCZ2ZXVzNyRjNLa09IQWpQUVorMGtIT1YKamdWRkVwR0kweERrSUFpb2VKVjVJWTd3MG53PT0K
  keystore-password: cGFzc3dvcmQ=
  truststore-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-password-config
  namespace: spark
  labels:
    app: kafka-spark-integration
    component: password-config
type: Opaque
stringData:
  kafka-client.properties: |
    security.protocol=SSL
    ssl.truststore.location=/etc/kafka/ssl/truststore.jks
    ssl.truststore.password=${TRUSTSTORE_PASSWORD}
    ssl.keystore.location=/etc/kafka/ssl/keystore.jks
    ssl.keystore.password=${KEYSTORE_PASSWORD}
    ssl.key.password=${KEYSTORE_PASSWORD}
    ssl.endpoint.identification.algorithm= 