# Пример создания secret для сертификатов Kafka
# Для реального применения используйте kubectl create secret вместо применения этого файла
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ssl-certs
  namespace: spark
type: Opaque
data:
  # значения должны быть закодированы в base64
  keystore.jks: ${BASE64_ENCODED_KEYSTORE}
  truststore.jks: ${BASE64_ENCODED_TRUSTSTORE}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ssl-passwords
  namespace: spark
type: Opaque
data:
  # значения должны быть закодированы в base64
  keystore-password: ${BASE64_ENCODED_KEYSTORE_PASSWORD}
  truststore-password: ${BASE64_ENCODED_TRUSTSTORE_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: adb-credentials
  namespace: spark
type: Opaque
data:
  # значения должны быть закодированы в base64
  url: ${BASE64_ENCODED_ADB_URL}
  username: ${BASE64_ENCODED_ADB_USERNAME}
  password: ${BASE64_ENCODED_ADB_PASSWORD} 