apiVersion: v1
kind: Service
metadata:
  name: spark-streaming
  namespace: spark
  labels:
    app: spark-streaming
spec:
  ports:
  - port: 4040
    name: ui
    targetPort: 4040
  selector:
    app: spark-streaming
  type: ClusterIP 